services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    environment:
      - VITE_BACKEND_URL=http://backend:8000
    networks:
      - medistock-shared

volumes:
  node_modules:

networks:
  medistock-shared:
    external: true
    name: backendmedistock_medistock-shared
